version: '3'

services:
    nextcloud:
        build:
            context: .
            dockerfile: Dockerfile
        image: ${NEXTCLOUD_IMAGE}

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: ${NGINX_IMAGE}

    db:
        build:
            context: ./docker/db
            dockerfile: Dockerfile
        image: ${DB_IMAGE}

    elasticsearch:
        build:
            context: ./docker/elasticsearch
            dockerfile: Dockerfile
        image: ${ELASTICSEARCH_IMAGE}

    coturn:
        build:
            context: ./docker/coturn
            dockerfile: Dockerfile
        image: ${COTURN_IMAGE}
